import string
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.hexdigits)
print(string.octdigits)
print(string.punctuation)
print(string.printable)
print(string.whitespace)
print(string.capwords("hello world"))
print(string.capwords("hello world", "o"))
print(string.capwords("hello world", " "))
print(string.capwords("hello world", "l"))
print(string.capwords("hello world", "h"))
print(string.capwords("hello world", "w"))
print(string.capwords("hello world", "d"))
print(string.capwords("hello world", "e"))
print(string.capwords("hello world", "r"))
print(string.capwords("hello world", "t"))
print(string.capwords("hello world", "y"))
print(string.capwords("hello world", "u"))
print(string.capwords("hello world", "i"))
print(string.capwords("hello world", "o"))
print(string.capwords("hello world", "p"))
print(string.capwords("hello world", "a"))